id: P010502
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-19 20:53:03.387462
source_metadata:
  id: bdr:W1EE23
  title: སྒྲོལ་དཀར་མའི་བསྟོད་པ།（སོག་ཡིག）
  author: ''
  volumes:
    d805bb2e380b4e0b9f3c96c008a196c5:
      image_group_id: I1KG16838
      title: ''
      volume_number: 1
      total_pages: 14
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
